version: '3.9'
services:
  wordpressdb:
    image: mariadb:10.10
    container_name: wordpressdb
    hostname: mariadb
    networks:
      - wordpress
    env_file:
      - .env/wordpressdb.env

  wordpress:    
    image: wordpress:6.1.1
    container_name: wordpress
    hostname: wordpress
    networks:
      - wordpress
    ports:
      - 8080:80
    depends_on:
      - keycloak
      - wordpressdb
      - web-api
      - signalr
    env_file:
      - .env/wordpress.env


  keycloakdb:
    image: mariadb:10.10
    container_name: keycloakdb
    hostname: keycloakdb
    networks:
      - auth
    env_file:
      - .env/keycloakdb.env
  
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    hostname: keycloak
    networks:
      - auth
      - backend
      - frontend
    env_file:
      - .env/keycloak.env
    ports:
      - 8083:8080
    command: start-dev
  
  neo4j:
    image: neo4j:5.5.0
    container_name: neo4j
    hostname: neo4j
    networks:
      - backend
    env_file:
      - .env/neo4j.env
    volumes:
      - ./data:/data
      - ./logs:/logs

  web-api:
    build:
      context: ./Backend
      dockerfile: ./WebApi/Dockerfile
    container_name: web-api
    hostname: web-api
    networks:
      - backend
      - frontend
    ports:
      - 8081:80
    depends_on:
      - keycloak
      - neo4j

    env_file:
      - .env/webapi.env

  signalr:
    build: 
      context: ./Backend
      dockerfile: ./Signalr/Dockerfile
    container_name: signalr
    hostname: signalr
    networks:
      - backend
      - frontend
    ports:
      - 8082:80
    depends_on:
      - keycloak
      - web-api
    env_file:
      - .env/signalr.env

networks:
  wordpress:
    driver: bridge
  auth:
    driver: bridge
  backend: 
    driver: bridge
  frontend:
    driver: bridge